// Get Todos
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';
export const FETCH_TODOS_FAILURE = 'FETCH_TODOS_FAILURE';

// Get Todo By Id
export const FETCH_SINGLE_TODO_SUCCESS = 'FETCH_SINGLE_TODO_SUCCESS';
export const FETCH_SINGLE_TODO_FAILURE = 'FETCH_SINGLE_TODO_FAILURE';

// Add Todos
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODOS_FAILURE = 'ADD_TODOS_FAILURE';

// Update Todos
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';
export const UPDATE_TODOS_FAILURE = 'UPDATE_TODOS_FAILURE';

// Delete Todos
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODOS_FAILURE = 'DELETE_TODOS_FAILURE';

